spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456789

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.
logging:
  level:
    root: warn
    com.lsc: info

  file:
    path: log
    name: blog-pro.log

server:
  port: 8081